<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\WatchParty.Domain\WatchParty.Domain.csproj" />
    <ProjectReference Include="..\..\src\WatchParty.Application\WatchParty.Application.csproj" />
    <ProjectReference Include="..\..\src\WatchParty.Infrastructure\WatchParty.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\WatchParty.PublicApi\WatchParty.PublicApi.csproj" />
    <ProjectReference Include="..\..\src\WatchParty.AdminApi\WatchParty.AdminApi.csproj" />
    <ProjectReference Include="..\..\src\WatchParty.Transcoding.Worker\WatchParty.Transcoding.Worker.csproj" />
  </ItemGroup>

</Project>